export const MODULE_ID          = 'reports';
export const API_SUB_URL        = '/reports';
export const API_SUB_URL_REPORT = '/reports';
export const API_SUB_URL_CONTRACT = '/contracts';
export const API_SUB_URL_NEW_HOP_DONG = '/new-contracts';
export const API_SUB_URL_REQUEST_TNMT_LAND_DATA_REPORT = '/request-tnmt-land-data-reports';
export const API_SUB_URL_REQUEST_LAND_DATA_OF_TNMT_REPORT = '/request-land-data-of-tnmt-reports';

export const REQUEST_TNMT_LAND_DATA_REPORT_LIST_FILTER_FORM_NAME          = 'REQUEST_TNMT_LAND_DATA_REPORT_LIST_FILTER_FORM';
export const REQUEST_TNMT_LAND_DATA_REPORT_LIST_FILTER_FORM_NAME_SUBMIT   = REQUEST_TNMT_LAND_DATA_REPORT_LIST_FILTER_FORM_NAME + '_SUBMIT';
export const REQUEST_TNMT_LAND_DATA_REPORT_LIST_FILTER_FORM_NAME_SUCCESS  = REQUEST_TNMT_LAND_DATA_REPORT_LIST_FILTER_FORM_NAME + '_SUCCESS';
export const REQUEST_TNMT_LAND_DATA_REPORT_LIST_FILTER_FORM_NAME_FAILURE  = REQUEST_TNMT_LAND_DATA_REPORT_LIST_FILTER_FORM_NAME + '_FAILURE';

export const LAND_DATA_OF_TNMT_REPORT_LIST_FILTER_FORM_NAME               = 'LAND_DATA_OF_TNMT_REPORT_LIST_FILTER_FORM';
export const LAND_DATA_OF_TNMT_REPORT_LIST_FILTER_FORM_NAME_SUBMIT        = LAND_DATA_OF_TNMT_REPORT_LIST_FILTER_FORM_NAME + '_SUBMIT';
export const LAND_DATA_OF_TNMT_REPORT_LIST_FILTER_FORM_NAME_SUCCESS       = LAND_DATA_OF_TNMT_REPORT_LIST_FILTER_FORM_NAME + '_SUCCESS';
export const LAND_DATA_OF_TNMT_REPORT_LIST_FILTER_FORM_NAME_FAILURE       = LAND_DATA_OF_TNMT_REPORT_LIST_FILTER_FORM_NAME + '_FAILURE';

export const ARCHIVE_BOOK_REPORT_LIST_FILTER_FORM_NAME               = 'ARCHIVE_BOOK_REPORT_LIST_FILTER_FORM';
export const ARCHIVE_BOOK_REPORT_LIST_FILTER_FORM_NAME_SUBMIT        = ARCHIVE_BOOK_REPORT_LIST_FILTER_FORM_NAME + '_SUBMIT';
export const ARCHIVE_BOOK_REPORT_LIST_FILTER_FORM_NAME_SUCCESS       = ARCHIVE_BOOK_REPORT_LIST_FILTER_FORM_NAME + '_SUCCESS';
export const ARCHIVE_BOOK_REPORT_LIST_FILTER_FORM_NAME_FAILURE       = ARCHIVE_BOOK_REPORT_LIST_FILTER_FORM_NAME + '_FAILURE';

export {PAGINATION_ITEMS_PER_PAGE} from '../../constants';